### ISSUE TITLE
Merkle Root and Address

### ISSUE THREAD

**Issue by hamed-ayoobi** [vsergeev/ntgbtminer#8]
Hello,

First of all, thank you for sharing your nice work with us.
I am pretty much new to bitcoin mining and I have two questions regarding your code.
My first question is about the Merkle root. I see that my generated Merkle root is different from the one which has been mined through the successful miner of that block. 
Does every miner have its own Merkle root and is it ok to have a different Merkle root from the successfully mined block? if yes, the nonce will be also different for each miner?
My second question is about the address used as the second parameter for the ntgbtminer.py. Shall we use the public key for this purpose? 
I know that my questions might be very much general and low-level but your answer would save a lot of time for me.
Thank you in advance for your response.

**Comment by vsergeev** [comment]
Hi @H-Ayoobi 

Yup, the merkle root will be different for every block template, since the transactions your Bitcoin node gathers from the mempool are changing all the time. Every miner working on a block will also have a different merkle root because 1) their coinbase transaction (to earn the mining reward) will be different and that is hashed into the merkle root, and 2) their view of the mempool is very likely different and prioritization of transactions may be different from other miners. And yeah, the nonce to solve the block will then be different too.

The second argument is the mining reward address. If the miner successfully solves a block and the network accepts it, this address will receive the block reward and transaction fees for the block.
